### ISSUE TITLE
r2dbc pool support

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-r2dbc#146]
I think supporting r2dbc pool will be nice to this project as well.

https://github.com/r2dbc/r2dbc-pool 

We can backport this to 1.1.x too. What do you think? @graemerocher

**Comment by graemerocher** [comment]
its already supported see https://github.com/micronaut-projects/micronaut-data/issues/1060#issuecomment-874799644 for example

**Comment by cemo** [comment]
I will open a PR to document it. <3
