### ISSUE TITLE
Exception with r2dbc-mysql for any date property

### ISSUE THREAD

**Issue by papahigh** [micronaut-projects/micronaut-r2dbc#23]
Hi!
Any CRUD operation on the entity with date field leads to RuntimeException when using with **r2dbc-mysql**.

I'm experiencing the following behavior: `any date field` is converted to `java.sql.Timestamp` and passed down to r2dbc driver. But it turns out that both`java.util.Date` and `java.sql.Timestamp` are not supported by `r2dbc-mysql`, please see the following [thread](https://github.com/mirromutth/r2dbc-mysql/issues/151). 

As a workaround, I've added codecs for handling Date and Timestamp locally, and it seems working. 
Could you please adjust the conversion rule for `DataType.TIMESTAMP` to be mapped to any `java.time.*` class?

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Please run `./gradlew test` in [example project](https://github.com/papahigh/micronaut-r2dbc-timestamp-issue).

### Expected Behaviour

Should be able to use date field in entities.

### Actual Behaviour

Runtime exception `io.micronaut.transaction.exceptions.TransactionSystemException: Error invoking doInTransaction handler: Cannot encode value of type 'class java.sql.Timestamp'`

### Environment Information

- **Operating System**: mac
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11.0.2

### Example Application

[https://github.com/papahigh/micronaut-r2dbc-timestamp-issue](https://github.com/papahigh/micronaut-r2dbc-timestamp-issue)

**Comment by safarmer** [comment]
I am seeing the same issue. The R2DBC driver does not know how to handle java.sql.Timestamp instances. It seems to be common across all of the dialect types.

Please see #24 for updated tests and a possible fix
